source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KVOController-Swift_Example', :exclusive => true do
  pod "KVOController-Swift", :path => "../"
end

target 'KVOController-Swift_Tests', :exclusive => true do
  pod "KVOController-Swift", :path => "../"

  
end
