source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KVOController_Example', :exclusive => true do
  pod "KVOController", :path => "../"
end

target 'KVOController_Tests', :exclusive => true do
  pod "KVOController", :path => "../"

  
end
